# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 800431a5d29ba88658b2819e0bc4c2db26345cebef37c0bc9fe57512c52e69b422c69178927bcb554490ee72c9d72fac3c67e4e6b85863aed06cd6ed2029c8f8

test:
  secret_key_base: 88b684aa084f527bb4d7505b82230f3559645d51749de1676cd91550b44ea2c28055b49d13cfbd5c614415a414e178fcf7dcc266b591c5cded96d06d6129e085

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
